version: '3'

services:
  # Pyhon container with flask
  api:
    build: 
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    image: vs/api
    container_name: vs-api
    restart: unless-stopped
    ### for testing:
    volumes:
      - ../backend:/usr/src/app
  
  # Best practise for flask
  # For coverage not only proxy
  api-proxy:
    image: nginx:stable-alpine
    container_name: vs-api-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes: 
      - ../backend/coverage:/usr/share/nginx/html/coverage
      - ./backend/nginx_coverage.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - api

  # React+Vite frontend build by npm builder
  frontend:
    build: 
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    image: vs/frontend
    container_name: vs-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
    ### for testing:
    #  - ../frontend:/usr/share/nginx/html
    depends_on:
      - api
      - api-proxy
# Porf. Dr. M.J.: Falls Sie bis hier gelesen haben: hoffentlich gefällt Ihnen die Implementation mit Docker :)