version: '3'

services:
  api:
    build: ../backend
    image: vs/api
    container_name: vs-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/usr/src/app
  frontend:
    build: ../frontend
    image: vs/frontend
    container_name: vs-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    ### DEV:
    #volumes:
    #  - ../frontend:/usr/share/nginx/html
    depends_on:
      - api
