version: '3'

services:
  api:
    build: 
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    image: vs/api
    container_name: vs-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    ### for testing:
    volumes:
      - ../backend:/usr/src/app
  frontend:
    build: 
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    image: vs/frontend
    container_name: vs-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    ### for testing:
    #volumes:
    #  - ../frontend:/usr/share/nginx/html
    depends_on:
      - api
